# Materials and Methods {#chapter02}

## Bacterial strains
The following bacterial strains were used in this study.

```{r table21, echo=FALSE, results='asis'}
table2_1 <- data.frame(Organism = c("_Thiosphaera pantotropha_ L.M.D. 92.63", "_Pseudomonas stutzeri_ A.T.C.C. 14405", "_Pseudomonas aeruginosa_ PAO1",
                                    "_Escherichia coli_ JM83", "_Escherichia coli_ JM109", "_Escherichia coli_ DH5&alpha;", "_Escherichia coli_ S17-1"),
                       Reference = c("Thompson et al. (1997); Robertson and Kuenen (1983)  [@thompson_variation_1997; @robertson_thiosphaera_1983]", "Döhler et al. (1983) [@dohler_transfer_1987]", "Holloway et al. (1979) [@holloway_chromosomal_1979]",
                                     "Yanisch-Perron et al. (1985) [@yanisch-perron_improved_1985]", "Yanisch-Perron et al. (1985) [@yanisch-perron_improved_1985]", "Hanahan (1983) [@hanahan_studies_1983]", "Simon et al. (1983) [@simon_broad_1983]"),
                       Source = c("Lab stock", "NCIMB culture collection", "NCIMB culture collection", "Lab stock", "Lab stock", "Lab stock", "Lab stock"))

kable(table2_1,
      caption = "Bacterial strains",
      booktabs = TRUE)
```

Tables of plasmids are given at the beginning of the chapter in which their construction is detailed.

## Growth media

### Luria-Bertani (LB) medium
For routine aerobic growth, all strains were grown in LB medium.

||concentration (g l$^{-1}$)|
|:-|-:|
|Tryptone|10|
|Yeast extract|5|
|NaCl|5|


50 ml cultures were grown in 250 ml flasks at 37 °C on a rotary shaker at 200-250 rpm.

### _T. pantotropha_ anaerobic minimal medium
_T. pantotropha_ was grown anaerobically, with nitrate (KNO$_3$, 20 mM) as the terminal electron acceptor and acetate (potassium acetate, 20 mM) as the carbon source, using the medium of Robertson and Kuenen (1983) [@robertson_thiosphaera_1983].

||Concentration (mM)|
|:-|-:|
|Na$_2$HPO$_4$|55|
|KH$_2$PO$_4$|11|
|NH$_4$Cl|6|
|MgSO$_4$.7H$_2$O|0.4|

Trace elements solution (Vishniac and Santer, 1957 [@vishniac_thiobacilli_1957]) was added at 2 ml l$^{-1}$.

||Concentration in stock trace elements solution (mM)|
|:-|-:|
|Na$_2$EDTA|140|
|Zn$_2$SO$_4$|7.6|
|CaCl$_2$.2H$_2$O|37|
|MnCl$_2$.4H$_2$O|25|
|FeSO$_4$.7H$_2$O|18|
|(NH$_4$)$_6$Mo$_7$O$_{24}$.4H$_2$O|0.9|
|CuSO$_4$.5H$_2$O|3.2|
|CoCl$_2$.6H$_2$O|6.7|

Starter cultures of _T. pantotropha_ were grown aerobically overnight at 37 °C. Anaerobic medium was then inoculated at a dilution of 1:100 and the cells were grown in completely filled bottles without shaking at 37 °C until the optical density at 650 nm (A$_{650}$) was 0.8-0.9.

### Minimal succinate medium
For some experiments _T. pantotropha_ was grown anaerobically in minimal succinate medium (Burnell et al., 1975 [@burnell_reversibility_1975]).

||Concentration (mM)|
|:-|-:|
|Sodium succinate|20|
|KNO$_3$|20|
|KH$_2$PO$_4$|5|
|(NH$_4$)$_2$HPO$_4$|4.5|
|CaCl$_2$|0.17|
|MgSO$_4$.7H$_2$O|0.1|
|FeNa.EDTA|0.05|

Hoagland's trace elements solution (Burnell et al., 1975 [@burnell_reversibility_1975]) was added at 100 $\mu$l l$^{-1}$.

||Concentration in stock trace elements solution (mM)|
|:-|-:|
|AlCl$_3$|2|
|KBr|1.2|
|LiCl|3|
|MnCl$_2$.2H$_2$O|12|
|H$_3$BO$_3$|50|
|ZnCl$_2$|2|
|CuCl$_2$|2|
|NiCl$_2$|2|
|CoCl$_2$|2|
|KI|0.84|
|SnCl$_2$.2H$_2$O|0.60|
|BaCl$_2$|0.67|
|Na$_2$MoO$_4$|0.67|
|NaVO$_3$.H$_2$O|0.20|
|Na$_2$SeO$_3$|0.80|

The medium was adjusted to pH 6.8. Starter cultures were grown aerobically overnight at 37 °C in minimal succinate medium with nitrate omitted. The anaerobic medium, with nitrate present, was then inoculated at a dilution of 1:100 and the cells grown in completely filled bottles without shaking at 37 °C until the A$_{650}$ was 1.2-1.3.

### _Ps. aeruginosa_ anaerobic medium
_Ps. aeruginosa_ PAO1 was grown anaerobically in LB medium (Section 2.2.1), supplemented with 50 mM KNO$_3$. Overnight starter cultures were inoculated into fresh medium at a dilution of 1:100 and grown in completely filled bottles, without shaking, to an A$_{650}$ of 1.2.


### _Ps. stutzeri_ anaerobic medium
_Ps. stutzeri_ ATCC 14405 was grown anaerobically using ACN medium (Coyle et al., 1985 [@coyle_nitrous_1985]).

||Concentration (mM)|
|:-|-:|
|L-asparagine|13.3|
|Tri-sodium citrate|23.8|
|KH$_2$PO$_4$|14.7|
|CaCl$_2$.6H$_2$O|0.46|
|MgSO$_4$|8.2|
|NaCl|345|
|KNO$_3$|9.9|

|Trace metals|Concentration ($\mu$M)|
|:-|-:|
|CuCl$_2$:2H$_2$O|1|
|FeCl$_3$|70|

Small cultures (50 ml in 250 ml flasks) were inoculated with a starter culture and grown overnight at 30 °C, on a rotary shaker at 100 rpm. This lowered the oxygen tension sufficiently to allow expression of denitrifying enzymes. Large cultures (20 l) were inoculated with 1 l of late-exponential culture and grown for 5 hours at 30 °C, whilst
sparging with air at a rate of 2-3 1 min$^{-1}$, then for 6 hours with no aeration. This cycle was repeated once, giving a total growth time of 22 hours, after which the cells were harvested at an A$_{650}$ of around 0.9.

### _E. coli_ anaerobic minimal medium
_E. coli_ JM83 was grown anaerobically using a medium based on that described by Pope and Cole (1982) [@pope_generation_1982].

||Concentration (mM)|
|:-|-:|
|KH$_2$PO$_4$|33|
|K$_2$HPO$_4$|46|
|trisodium citrate|1.7|
|(NH$_4$)$_2$SO$_4$|7.6|
|Fumaric acid pH 7.0|40|
|NaNO$_2$|5|

|Trace metals|Concentration ($\mu$M)|
|:-|-:|
|Na$_2$SeO$_4$.10H$_2$O|1|
|Na$_2$MoO$_4$.2H$_2$O|1|

Sulphur-free trace metals solution (Cole et al., 1974 [@cole_nitrite_1974]) was added at 1 ml l$^{-1}$.

||Concentration in stock trace elements solution (mM)|
|:-|-:|
|MgCl$_2$:6H$_2$O|403|
|MnCl$_2$:4H$_2$O|50.5|
|FeCl$_3$.6H$_2$O|14.8|
|CaCl$_2$.6H$_2$O|4.6|

The medium also contained 0.4% v/v glycerol and 5% v/v Luria-Bertani medium (Section 2.2.1). Overnight starter cultures grown aerobically in LB medium were inoculated at a dilution of 1:100 and the cultures were incubated at 37 °C in completely filled bottles without shaking.

### Growth on solid medium
Strains were grown on plates containing the media described above using the addition of 1.5% w/v bacteriological agar.

### Antibiotics and other selective additions to media
Antibiotics were used to select for cells carrying plasmids or to counter-select for one organism against another, at the following concentrations (in $\mu$g ml$^{-1}$): ampicillin (100), kanamycin (25 for _E. coli_, 100 for _T. pantotropha_), rifampicin (100), spectinomycin (25 for _E. coli_, 100 for T. pantotropha), streptomycin (50 for _E. coli_, 100 for _T. pantotropha_), carbenicillin (250). Lead nitrate was also used at a concentration of 1 mM to select for _T. pantotropha_ following conjugative transfer of plasmids from _E. coli_ S17-1 (Section 2.5.20). _Ps. aeruginosa_ was selected for following the same procedure using _Pseudomonas_ selective medium supplements (Oxoid). Plates used for this purpose contained 200 $\mu$g ml$^{-1}$ of cetrimide and 15 $\mu$g ml$^{-1}$ of sodium nalidixate.

For blue-white selection of plasmids by $\alpha$-complementation in _E. coli_, isopropylthio-$\beta$-D-galactoside (IPTG) and 5-bromo-4-chloro-3-indolyl-$\beta$-D-galactoside (X-Gal) were used at concentrations of 1 mM and 100 mM, respectively. IPTG was also used at concentrations of 0.5-1 mM to induce transcription from plasmids containing the _tac_ promoter (de Boer et al., 1983 [@de_boer_tac_1983]).

## Protein biochemistry techniques

### Preparation of total soluble extracts
Soluble extracts for protein analysis were prepared from cells by sonication or by a freeze-thaw lysozyme procedure (Berks et al., 1993 [@berks_purification_1993]). For sonication, cells were grown to mid-exponential phase, harvested by centrifugation and resuspended in 50 mM Tris-HCl pH 8.0. The cell suspension was sonicated in an ice bath by 12 rounds of sonication (MSE sonicator tuned to 7-8 $\mu$m amplitude) for a duration of 30 seconds, separated by 30 second pauses to prevent overheating. Broken cells were then ultracentrifuged for 45 minutes at 183 000 g, 4 °C, to pellet membrane material. Soluble extracts were also prepared from _Ps. aeruginosa_ using a freeze-thaw lysozyme procedure. Following centrifugation, the harvested cells were resuspended in 5 ml of Tris-HCl, pH 8.0, per litre of original culture and lysozyme was added to a concentration of 1 mg ml$^{-1}$. The sample was incubated for 10 minutes at 37 °C, then frozen at -70 °C for 30 minutes. The cells were then thawed at room temperature and the cycle was repeated once more. The sample was incubated with a few crystals of DNase for 10 minutes at 37 °C, then centrifuged at 40 000 g for 30 minutes at 4 °C. The supernatant was filtered once through Whatman 3MM paper and used as the final total soluble extract.

### Preparation of periplasmic extracts
Periplasmic fractions were prepared from cells of _T. pantotropha_ by the method of spheroplasting. Cells were grown to late exponential phase, harvested by centrifugation and resuspended in 20 ml per litre of original culture of 0.5 M sucrose, 50 mM Tris-HCl pH 8.0, 3 mM EDTA. Lysozyme was added to a concentration of 1 mg ml$^{-1}$ and the mixture was incubated at 37 °C for 30 minutes. The mixture was then centrifuged at 18 000 g for 30 minutes, producing a pellet of spheroplasts and a supernatant containing periplasmic proteins. _Ps. aeruginosa_ was spheroplasted in a similar way, except EDTA was omitted and the incubation at 37 °C was for 1 hour.

### Protein purification
All protein purification was carried out at 4 °C. Column sizes, loading capacity and flow rates were determined according to information in Scopes (1987) [@scopes_protein_1987]. Flow rates were controlled with a peristaltic pump (P-1, Pharmacia Biotech) and fractions were collected using a RediFrac fraction collector (Pharmacia Biotech).

#### Ion exchange chromatography
Ion-exchange chromatography was employed not only as a first step in the purification of cytochrome _cd_$_1$ from _Thiosphaera pantotropha_ but also as a general first step in all protein purifications. Extracts for purification were prepared in 50 mM Tris-HCl buffer, pH 8.0 at 4 °C. Columns of sizes 1 x 10 cm and 2.6 x 40 cm were generally used. The columns were packed with DEAE-Sepharose CL6B (Pharmacia Biotech) and equilibrated with 50 mM Tris-HCl, pH 8.0 (start buffer). Extract was loaded onto the column and non-specifically bound material was washed through with 3 column volumes of start buffer. Fractions were eluted using a linear gradient of 0-400 mM NaCl in 50 mM Tris-HCl pH 8.0, using a volume and fraction size appropriate to the column.

#### Hydrophobic interaction chromatography
Cytochrome _cd_$_1$ was further purified using hydrophobic interaction chromatography on Phenyl-Sepharose CL-4B columns (Pharmacia Biotech). Protein extracts in 50 mM Tris HCl pH 8.0 were brought to 40% saturation with (NH$_4$)$_2$SO$_4$ using the formula of Scopes (1987) and gently stirred at 4 °C. Columns of 1 x 10 cm were packed and equilibrated in 50 mM Tris-HCl pH 8.0, 40% saturated (NH$_4$)$_2$SO$_4$ (start buffer). Samples were loaded and washed with 3 volumes of this start buffer. Proteins were eluted with a linear gradient of 40-0% saturation (NH$_4$)$_2$SO$_4$ in 50 mM Tris-HCl pH 8.0.

#### Size exclusion chromatography (gel filtration)
Proteins were further purified by gel filtration using columns of Sephacryl S-200 HR (Pharmacia Biotech). Columns of 2.6 x 100 cm were packed and equilibrated with 20 mM Tris-HCl pH 8.0, 100 mM NaCl according to the manufacturer's instructions and run at 10-20 ml h$^{-1}$. Samples were concentrated to about 4 ml before application, using an Amicon ultrafiltration cell with a 10 kDa cut-off membrane.

### Sodium dodecyl sulphate polyacrylamide gel electrophoresis (SDS-PAGE)
Protein samples were analysed in whole cell extracts or during purification using size fractionation by SDS-PAGE. Gels of an appropriate percentage acrylamide (from a stock of acrylamide plus N, N'-methylenebisacrylamide in the ratio 30:0.8) were prepared according to Sambrook et al. (1989) [@sambrook_molecular_1989] and cast using a Mini Protean II apparatus (BioRad). Stacking gels contained 5% acrylamide, 130 mM Tris-HCl pH 6.8 and 0.1% w/v SDS. Resolving gels contained 6-15% acrylamide (depending on the range of separation required), 375 mM Tris HCl pH 8.8 and 0.1% w/v SDS. Polymerisation of gels was initiated with 0.1% w/v ammonium persulphate and 0.1% v/v TEMED (N, N, N’, N’-tetramethylethylenediamine). Samples at an appropriate concentration were denatured by boiling for 5 minutes with 5 $\mu$l of sample buffer (50 mM Tris-HCl pH 6.8, 100 mM dithiothreitol, 2% w/v SDS, 0.1% w/v bromophenol blue, 10% glycerol), in a total volume of 20 $\mu$l, and separated at 180 V for 45 minutes. Electrophoresis buffer contained 25 mM Tris, 250 mM glycine pH 8.3, 0.1% w/v SDS.

#### Coomassie Blue stain for proteins
After electrophoresis, total protein was detected on gels by staining with Coomassie Brilliant Blue R250 (0.5% w/v), in 50% v/v methanol, 10% v/v acetic acid, for 1 hour at room temperature. Gels were destained with 30% v/v methanol, 10% v/v acetic acid, until the background was clear. For storage, gels were either vacuum-dried on filter paper at 80 °C, after soaking in 10% v/v glycerol for several hours, or dried between cellulose sheets using the Promega gel drying system.

#### Haem stain
Following separation by SDS-PAGE, _c_-type cytochromes were stained for haem using the method of Goodhew et al. (1986) [@goodhew_cytochromes_1996]. Before electrophoresis, protein samples were denatured in sample loading buffer without dithiothreitol, as this reduces the intensity of the stain. The gel was soaked in 70 ml of 0.25 M sodium acetate, pH 5.2, for 30 minutes. 30 mg of 3, 3, 5, 5°-tetramethylbenzidine dissolved in 30 ml of methanol was added and the gel was incubated for a further 30 minutes. Staining was initiated by the addition of 0.3 ml of 30% v/v hydrogen peroxide and the gel was incubated with gentle shaking in the dark. After full development, the gel was washed twice in 50 ml of 70% v/v 0.25 M sodium acetate pH 5.2, 30% v/v isopropanol and stored in water in the dark.

#### Western blotting
Cytochrome _cd_$_1$ from _Thiosphaera pantotropha_ was detected immunologically after SDS PAGE by Western blotting. Protein extracts were separated on 6% acrylamide gels and transferred to nitrocellulose membranes using semi-dry transfer buffer (50 mM Tris, 38 mM glycine pH 8.3, 0.04% w/v SDS, 20% v/v methanol) as an electrolyte in a Pharmacia LKB Novablot electroblotting apparatus. After transfer, the gel was blocked for 1 hour in PBS-A-T buffer (8.1 mM Na$_2$HPO$_4$, 1.5 mM KH$_2$PO$_4$ pH 7.4, 140 mM NaCl, 7.7 mM NaN$_3$, 0.3% v/v Tween-20) plus 1% w/v skimmed milk powder (blocking buffer). The membrane was washed in PBS-A-T plus 0.3% w/v skimmed milk powder (wash buffer), then incubated for two hours in blocking buffer containing mouse anti-cytochrome _cd_$_1$ antibody (obtained from Thon de Boer, Vrije Universiteit, Amsterdam), at a dilution of 1/1000. The membrane was washed three times for five minutes each time with wash buffer, then incubated for two hours with anti-rabbit antibody-alkaline phosphatase conjugate, also diluted to 1/1000. After three more five minute washes in wash buffer, the membrane was washed four times with PBS-A-T buffer and equilibrated for 1 minute in TBS buffer (100 mM Tris-HCl pH 9.5, 100 mM NaCl). Bound antibody was detected colorimetrically by incubating the membrane in TBS buffer containing 10 mM MgCl$_2$, 200 $\mu$M nitroblue tetrazolium and 20 $\mu$M 5-bromo-4 chloro-3-indolyl phosphate. Development was stopped by several washes of distilled water and membranes were stored in TE buffer (10 mM Tris-HCl pH 8.0, 1 mM EDTA) in the dark.


### Determination of protein concentration
Protein concentrations were estimated using the method of Bradford (1976) [@bradford_rapid_1976] and the BioRad reagent kit. 20 $\mu$l of diluted sample was mixed with 0.8 ml of distilled water and 0.2 ml of reagent and incubated at room temperature for 10 minutes. Absorbance at 595 nm was recorded and converted to protein concentration in mg ml$^{-1}$ using a standard curve prepared with known concentrations of bovine serum albumin.

### UV-visible spectroscopy
UV and visible spectra of protein samples were recorded on a Perkin Elmer Lambda 2 spectrophotometer, interfaced to a Dell 316SX PC running Perkin Elmer spectroscopy software.

### Assays for enzyme activity

#### Cytochrome _cd_$_1$ nitrite reductase assay
Nitrite reductase activity of cytochrome _cd_$_1$ was routinely measured using reduced methyl viologen as an electron donor. Assays were performed in a 1 ml cuvette containing 50 mM Tris-HCl pH 8.0, 5 mM EDTA, 1 mM methyl viologen and an aliquot of sample. The cuvette was sealed with a rubber septum, evacuated and flushed with argon. 1-2 $\mu$l of sodium dithionite (approximately 5 mg ml$^{-1}$) was added to reduce the methyl viologen, giving a blue colour. After checking that the background rate of reduction was close to zero, the reaction was initiated by the addition of 10 mM KNO$_2$. Oxidation of methyl viologen was followed by the decrease in absorbance at 600 nm over time. The rate was converted to a specific activity using the extinction coefficient for reduced methyl viologen at 600 nm ($\epsilon_{600}$) of 13 mM$^{-1}$ cm$^{-1}$ (Moir 1993 [@moir_aspects_1993]).


#### Cytochrome _cd_$_1$ cytochrome oxidase assay
The oxidase activity of cytochrome _cd_$_1$ from _T. pantotropha_ was assayed using horse heart cytochrome _c_ as an electron donor. To prepare pre-reduced cytochrome _c_, 35 mg of cytochrome _c_ was dissolved in 2.5 ml of 200 mM KH$_2$PO$_4$, pH 7.4, that contained 1 mg ml$^{-1}$ of sodium dithionite. Excess sodium dithionite was removed by passage through a Sephadex PD-10 column, equilibrated with the same buffer. Cytochrome _cd_$_1$ was assayed in a volume of 1 ml containing 50 mM Tris-HCl pH 8.0 and 25 $\mu$M of reduced cytochrome _c_. The assay was started with the addition of an aliquot of cytochrome _cd_$_1$ and the oxidation of the cytochrome _c_ was followed by the decrease in its absorbance at 550 nm. A difference extinction coefficient of 18.5 mM$^{-1}$ cm$^{-1}$ (Robinson et al., 1979 [@robinson_implications_1979]) was used to calculate the rate of activity.

#### Cytochrome _c_ peroxidase assay
Cytochrome _c_ peroxidase from _T. pantotropha_ was assayed using reduced horse heart cytochrome _c_ as an electron donor, based on the method of Gilmour et al. (1994) [@gilmour_kinetics_1994]. Pre-reduced cytochrome _c_ was prepared as described in the above section. Aliquots of the sample to be assayed were incubated in a 1 ml cuvette containing 50 mM Tris-HCl, pH 8.0, and 25 $\mu$M reduced cytochrome _c_. The assay was initiated after 40-60 s by the addition of hydrogen peroxide to a final concentration of 18 $\mu$M and the activity was followed by the decrease in absorbance at 550 nm, as described for the cytochrome oxidase assay.


#### Assay of nitrite produced by _in vivo_ nitrite reductase activity
Nitrite that had accumulated in the medium of _T. pantotropha_ or _Ps. aeruginosa_ cultures during denitrification was assayed colorimetrically using the method of Nicholas and Nason (1957) [@donald_nicholas_determination_1957]. 1 ml samples of the culture were centrifuged to pellet the cells and a 50 $\mu$l aliquot of the supernatant (diluted where necessary) was mixed with 3.7 ml of 1% w/v sulphanilamide in 1 M HCl. 0.3 ml of 0.02% w/v N-(1-napthyl) ethylene diamine hydrochloride was added and the samples were incubated at room temperature for 20 minutes. The absorbance at 540 nm was recorded and the concentration of nitrite was calculated from a standard curve of known nitrite concentrations in the range 0-1 mM.

### Chemical preparation of semi-apo cytochrome _cd_$_1$
Haem _d_$_1$ was removed from cytochrome _cd_$_1$, giving the _c_-haem containing semi-apo enzyme, by the method of Hill and Wharton (1978) [@hill_reconstitution_1978]. 2 ml of purified protein (2 mg ml$^{-1}$) in 50 mM Tris-HCl pH 8.0 was mixed with 18 ml of acetone containing 24 mM HCl. The solution was incubated at 37 °C for 20 minutes and centrifuged at 4000 g, 4 °C for 2 minutes. The red pellet of precipitated protein was washed twice with acetone/HCl and twice with acetone, then redissolved in 2 ml of 50 mM Tris-HCl pH 9.0, 6 M urea. This solution was dialysed overnight at 4 °C against 50 mM Tris-HCl pH 8.0. Samples were analysed by spectroscopy in the oxidised and reduced forms to confirm the presence of only _c_-type haem.

### Purification of haem _d_$_1$
Haem _d_$_1$ was purified during the preparation of semi-apo cytochrome _cd_$_1$, described above. After centrifugation of the semi-apo protein, 8 volumes of the green supernatant (containing haem _d_$_1$) was extracted with 1 volume of 1.2 M NaOH. Haem _d_$_1$ dissolved in the lower aqueous layer and was removed with a pipette. The pH of the solution was adjusted to 7 with 1 M HCl and the solution was stored at 4 °C in the dark. The haem concentration was estimated from the absorbance of the pyridine haemochromogen at 620 nm using an extinction coefficient of 24 mM$^{-1}$ cm$^{-1}$ (Hill and Wharton, 1978 [@hill_reconstitution_1978]).

## Genetic techniques

### DNA manipulation

#### Organic solvent extraction and precipitation of nucleic acids
Nucleic acids were purified and concentrated after enzymatic manipulation by organic solvent extraction and ethanol precipitation. An equal volume of phenol:chloroform:isoamyl alcohol (25:24:1) was mixed with the sample by vortexing and the phases were separated by centrifugation at 15 000 g for two minutes. The upper aqueous phase was mixed with 0.1 volumes of 3 M sodium acetate pH 5.2 and 2.5 volumes of cold ethanol and incubated at -70 °C for 30 minutes. Nucleic acids were pelleted by centrifugation at 15 000 g for 15 minutes, then washed with 100 $\mu$l of ice-cold 70% v/v ethanol by centrifuging for a further five minutes. The pellet was air-dried, then redissolved in TE buffer or sterile distilled water.

#### Purification of plasmid DNA
Plasmid DNA was purified from bacteria by three methods, depending on the quality required for subsequent experiments. For restriction digests, analysis and cloning, the alkaline lysis miniprep procedure was used (Birnboim and Doly, 1979 [@birnboim_rapid_1979]). 1.5 ml of an overnight culture was harvested in a microcentrifuge and resuspended in 300 $\mu$l of 25 mM Tris-HCl pH 8.0, 50 mM glucose, 10 mM EDTA. The cells were lysed by the addition of 600 $\mu$l of 0.2 M NaOH, 1% w/v SDS. Protein and chromosomal DNA were then precipitated by the addition of 450 $\mu$l of 3 M potassium acetate, 11.5 % v/v glacial acetic acid pH 4.8. The precipitate was removed by centrifugation at 15 000 g for 15 minutes. 800 $\mu$l of supernatant was treated with 20 $\mu$g ml$^{-1}$ of DNase-free RNase A at 37 °C for 20 minutes. Plasmid DNA was precipitated with 0.8 volumes of isopropanol and pelleted by centrifugation at 15 000 g for 15 minutes. Finally, the pellet was washed with ice-cold 70% v/v ethanol by centrifugation for five minutes, drained, air-dried and redissolved in 50 $\mu$l of TE buffer (10 mM Tris-HCl pH 8.0, 1 mM EDTA). Plasmid DNA was stored at -20 °C. 

Plasmid DNA of higher purity for sequencing was purified by either PEG precipitation (Mierendorf and Pfeffer, 1987 [@mierendorf_direct_1987]) or using the Wizard plasmid DNA purification kit (Promega). In the first method, the alkaline lysis procedure was followed up to the RNase A treatment, after which the sample was extracted once with 400 $\mu$l of phenol:chloroform. After precipitation, washing and drying of the plasmid DNA, the pellet was redissolved in 16 $\mu$l of sterile distilled water and thoroughly mixed with 4 $\mu$l of 4 M NaCl and 20 $\mu$l of 13% w/v polyethylene glycol (PEG 8000). The sample was incubated on ice for 30 minutes, then centrifuged at 15 000 g for 15 minutes to pellet the plasmid DNA. The pellet was then washed with 70% v/v ethanol, dried and redissolved in 20 $\mu$l of sterile distilled water.

The Promega Wizard kit was used according to the manufacturer's instructions. Cell lysis and the production of a cleared supernatant were performed much as described for the alkaline lysis miniprep. Plasmid DNA was then mixed with DNA binding resin, absorbed onto a minicolumn and washed with wash solution (80 mM potassium acetate, 8.3 mM Tris HCl pH 7.5, 40 $\mu$M EDTA, 55% v/v ethanol). The purified plasmid DNA was eluted in 40-50 $\mu$l of prewarmed (70 °C) TE buffer, by a brief centrifugation.


#### Restriction digestion of DNA
Plasmid and chromosomal DNA was digested with restriction enzymes to allow cloning of DNA fragments and to analyse recombinant plasmids. Plasmid DNA was digested in a volume of 20 $\mu$l (or 40 $\mu$l for preparative digests), containing the appropriate restriction enzyme buffer (New England Biolabs), 5-10 units of restriction enzyme and 1 mg ml$^{-1}$ of bovine serum albumin where recommended, for one hour at the correct temperature (normally 37 °C, 25 °C for _SmaI_). Chromosomal DNA (usually 5-10 $\mu$g) was digested for 4-8 hours. Digestion was stopped with 25 mM Na EDTA or by heating at the recommended inactivation temperature.

#### Conversion of cohesive DNA ends to blunt ends using T4 DNA polymerase
Cohesive DNA ends produced by restriction digestion were converted to blunt ends for cloning into plasmids digested with “blunt cutters” such as _Smal_ or _EcoRV_. After digestion and inactivation of the restriction enzyme, digests were extracted with an equal volume of phenol:chloroform and precipitated. The DNA was then redissolved in 20 $\mu$l of sterile distilled water, containing T4 polymerase buffer (10 mM Tris-HCl pH 7.9, 50 mM NaCl, 10 mM MgCl$_2$, 1 mM DTT, 50 $\mu$g ml BSA), 100 $\mu$M of each deoxynucleotide triphosphate and 3 units of T4 DNA polymerase (New England Biolabs). The mixture was incubated at 37 °C for five minutes, 15 °C for 20 minutes, then heat-inactivated at 75 °C for 10 minutes.


#### Dephosphorylation of plasmid DNA
Vector DNA was dephosphorylated before cloning to prevent religation of the vector in difficult clonings such as those without blue-white selection (Section 2.3.8), or into sites cut with a single blunt cutting enzyme. After digestion, the volume of the reaction mixture was increased to 200 $\mu$l with sterile distilled water and shrimp alkaline phosphatase buffer (20 mM Tris-HCl pH 8.8, 10 mM MgCl$_2$) and 2 units of shrimp alkaline phosphatase (United States Biochemical) was added. The mixture was incubated at 37 °C for 30 minutes, then at 65 °C for 20 minutes to inactivate the enzyme. DNA was recovered by extraction with an equal volume of phenol:chloroform, followed by ethanol precipitation.

#### Ligation of DNA fragments into plasmid vectors
DNA fragments with either blunt or cohesive termini were cloned into plasmid vectors using T4 DNA ligase. Ligations were performed in a volume of 20 $\mu$l, containing ligase buffer (50 mM Tris-HCl pH 7.8, 10 mM MgCl$_2$, 10 mM DTT, 1 mM ATP, 25 $\mu$g ml$^{-1}$ bovine serum albumin), 400 units of T4 DNA ligase and various proportions of vector and insert DNA, to generate the optimum number of clones containing an insert. Cohesive end ligations were usually incubated at 15 °C for one hour, then at 4 °C overnight. Blunt end ligations were usually incubated at 15 °C overnight. Ligation mixtures were stored at -20 °C until used for transformation.

#### Agarose gel electrophoresis
Restricted DNA was separated by size fractionation using agarose gel electrophoresis, for analysis of recombinant plasmids and separation of fragments for purification. After restriction, 0.1 volumes of sterile loading dye (10 mM EDTA, 50% v/v glycerol, 0.5% w/v bromophenol blue) was added. For analysis of digested plasmids, gels of 50 ml volume (106 x 78 x 6 mm) and 0.6-1.4% w/v agarose were most often used. These gels were run in TBE buffer (45 mM Tris-borate pH 8.3, 1 mM EDTA) at a constant current of 50-60 mA. For subsequent DNA purification, TAE buffer (40 mM Tris-acetate pH 8.0, 1 mM EDTA) was used instead. Ethidium bromide was added to the gel and the electrophoresis buffer at a concentration of 0.2 $\mu$g ml$^{-1}$ to stain the DNA. Stained gels were viewed and photographed under ultraviolet illumination.

#### Purification of DNA fragments from agarose gels
DNA fragments were purified from TAE agarose gels for subsequent manipulation, using either the GeneClean II kit (BIO 101 Inc.) or the Wizard PCR prep kit (Promega). In the first procedure, the desired fragment was excised from the gel using a clean razor blade and dissolved in 1 ml of 6 M sodium iodide solution for five minutes at 50 °C. 5 $\mu$l of Glassmilk (a DNA binding silica matrix) was added and the mixture was incubated on ice for 15 minutes. The Glassmilk was pelleted by a brief centrifugation, then washed three times in 1 ml of NEW Wash (an ethanol-based buffered salt solution) and pelleted again. The pellet was air-dried for 10 minutes, then the DNA was eluted in 10-20 $\mu$l of TE buffer, by incubating at 50 °C for 2-3 minutes, pelleting the resin by centrifugation and retaining the supernatant.

Using the Promega Wizard PCR prep kit, the gel slice was dissolved in 1 ml of DNA binding resin by incubation at 50 °C for five minutes. The resin was absorbed onto a minicolumn and washed with 2 ml of 80 % v/v isopropanol. Finally, DNA was eluted with 40-50 $\mu$l of prewarmed TE buffer (70 °C) by a brief centrifugation. The yield of purified
DNA fragment was analysed by agarose gel electrophoresis in TBE buffer.

#### Transformation of competent _E. coli_ with plasmid DNA
_E. coli_ strains were transformed with plasmid DNA by two methods: chemical transformation using CaCl$_2$ (Cohen et al., 1972 [@cohen_nonchromosomal_1972]) and electroporation. For chemical transformations, an overnight culture of _E. coli_ was reinoculated in 50 ml of LB medium at a dilution of 1/100 and grown to an absorbance at 650 nm of 0.3-0.5. The cells were harvested by centrifugation, resuspended in 10 ml of 0.1 M MgCl$_2$ and incubated on ice for 15 minutes. Cells were then harvested once more, resuspended in 1 ml of 0.1 M CaCl$_2$ and incubated on ice for one hour. At this stage, the competent cells could be stored at -70 °C in 25% v/v glycerol for several months. To transform the cells, a 100 $\mu$l aliquot was mixed with 10 $\mu$l of a ligation reaction, or 1-2 $\mu$l of a plasmid purified by the alkaline lysis miniprep protocol, and incubated on ice for a further 45 minutes. The cells were then heat-shocked at 42 °C for 30 seconds in thin-walled polypropylene tubes, placed on ice and mixed with 1 ml of LB medium. Cells were left to recover for 90-120 minutes, with shaking at 37 °C, before plating out on a medium selective for the presence of the plasmid.

For electroporation, _E. coli_ was grown to an A$_{650}$ of 0.5-1.0 and harvested by centrifugation. The pellet was then repeatedly resuspended and harvested in decreasing volumes of ice-cold sterile water in the following order: 1 volume, 0.5 volumes, 0.5 volumes and 0.02 volumes. After the final wash the cells were harvested once more and resuspended in 0.02 volumes of sterile 10% v/v ice-cold glycerol. 40 $\mu$l aliquots of cells were mixed with 1 $\mu$l of ligation mix (diluted 1:4 in sterile water) in a 1 ml electroporation cuvette (BioRad). The cells were given a pulse of 2500 V in a BioRad E. coli Pulser, mixed with 1 ml of LB and left to recover at 37 °C for one hour. Several dilutions were plated out on medium selective for the presence of the plasmid.

#### Transformation of Gram-negative bacteria by mating with _E. coli_ S17-1
_E. coli_ S17-1 has the _tra_ genes of the RP4 plasmid integrated into its chromosome, allowing the transfer of plasmids that contain an origin of transfer (Mob site) to a recipient Gram-negative bacterium via a sex pilus (Simon et al., 1983 [@simon_broad_1983]). Donor _E. coli_ cells containing the plasmid and the recipient strain were both grown to an A$_{650}$ of 0.5-1.0. The cells were harvested by centrifugation, washed twice with LB medium and harvested in 0.3 ml of LB. Harvested cells were then mixed, pipetted onto a sterile nitrocellulose filter on an LB plate and incubated overnight at 37 °C. The mated cells were harvested from the filter in 0.8 ml of LB. Serial dilutions of the mating mix were then plated onto medium which was selective for both the plasmid and the recipient strain and incubated at 37 °C until single colonies appeared. These were isolated and further analysed to confirm the presence of the plasmid and that the colonies were of the recipient bacterium.

#### Preparation of chromosomal DNA
Chromosomal DNA from _T. pantotropha_ was isolated by two methods, depending on the yield required. For large-scale isolation, 200 ml cultures were grown aerobically overnight on LB medium. The culture was divided into 50 ml portions and harvested by centrifugation. Each pellet was washed in 2.5 ml STE buffer (10 mM Tris-HCl pH 8.0,
100 mM NaCl, 1 mM EDTA) and resuspended in 15 ml STE buffer. SDS was added to a concentration of 0.15% w/w and the lysate was incubated at 37 °C for 90-180 minutes with 5 units each of proteases PS147 and P4880 (Sigma). The mixture was extracted with 20 ml of phenol:chloroform by gentle mixing for 10 minutes and centrifuged at 4000 g for 45 minutes. The aqueous phases were re-extracted twice with chloroform and pooled in a sterile 250 ml beaker. DNA was precipitated overnight at -20 °C with 10 ml of 3 M sodium acetate pH 5.2 and 100 ml ethanol. The DNA was then spooled onto a glass rod and left to dissolve in 2 ml of TE buffer at 4 °C for 2-3 days. DNA concentration and purity were determined by the absorbance ratio A$_{260}$:A$_{280}$ and restriction of the DNA analysed by agarose gel electrophoresis.

Smaller scale purification was performed using the Promega Wizard genomic DNA purification kit, largely according to the manufacturer's instructions. Using this procedure, 1 ml of overnight culture was lysed and treated with RNase, after which protein was precipitated and removed by centrifugation. Chromosomal DNA was then precipitated by
isopropanol, washed with 70% v/v ethanol, and dissolved in TE buffer overnight at 4 °C.

#### Polymerase chain reaction methods
The polymerase chain reaction (PCR) was routinely used to generate DNA fragments for cloning and sequencing. Many variations of the technique were used; however, a typical reaction (50 $\mu$l) contained 10-500 ng of template genomic DNA, PCR buffer (10 mM Tris HCl pH 9.0, 50 mM KCl, 0.1% Triton X-100), 1.5 mM MgCl$_2$, 0.2 mM each dNTP, 25 pmol of forward and reverse primers and 2.5 units of Taq DNA polymerase. Amplification was performed in 0.5 ml thin-walled Eppendorf tubes, in a programmable thermocycler (MJ Research Inc.). A typical cycle would consist of denaturation (97 °C, 3 minutes), followed by 30 cycles of denaturation (94 °C, 1 minute), primer annealing (55 °C, 2 minutes) and extension (72 °C, 2 minutes), with a final extension step of 72 °C for 10 minutes. PCR products were analysed by electrophoresis on agarose gels in TBE buffer.

Taq polymerase catalyses the addition of a single dNTP residue (normally dATP, Clark 1988 [@clark_novel_1988]) to the 3' end of PCR products, which allows them to be cloned into linearised vectors with a 5' dTTP overhang. The pGEM-T cloning kit (Promega) was used for this purpose. Typically, 5 $\mu$l of a PCR product purified by the GeneClean method was ligated to 1 $\mu$l of PGEM-T vector in a 10 $\mu$l reaction, as described previously. The ligation mix was used to transform competent cells as described in Section 2.5.19.

#### Southern blotting of DNA using the digoxigenin detection system
Probes for Southern blotting were generated by random priming of DNA fragments using hexanucleotides, Klenow DNA polymerase and a deoxynucleotide triphosphate mixture containing dUTP coupled to digoxigenin (DIG-11-UTP). The latter was detected on a membrane using antibodies to digoxigenin, which were coupled to alkaline phosphatase. To
generate the probe, approximately 1 $\mu$g of DNA template (a restriction fragment or PCR product homologous to the region to be probed) was denatured by boiling and chilled in an ice-brine mixture. 10 $\mu$l of denatured DNA was mixed with 2 $\mu$l of DIG labelling mix (1 mM DATP, SCTP and DGTP, 6.5 mM UTP, 0.35 mM HTTP, 0.35 mM DIG-11-UTP), 2 $\mu$l random hexanucleotides (62.5 A$_{260}$ units ml$^{-1}$) and 5 units of Klenow fragment in a total volume of 20 $\mu$l and incubated at 30 °C overnight. Probe DNA was precipitated with 0.1 volumes of 4 M LiCl and 2.5 volumes of ethanol, washed with ice-cold 70% v/v ethanol, air dried and redissolved in 20 $\mu$l of TE buffer.

The DNA to be probed was separated by agarose gel electrophoresis and transferred overnight at room temperature to a positive nylon membrane by capillary transfer with 0.4 M NaOH. The membrane was then prehybridised at 68 °C for one hour in 20 ml of hybridisation buffer (5x SSC, 1% w/v blocking reagent, 0.1% w/v N-laurylsarcosine, 0.02%
w/v SDS). Approximately 0.5 $\mu$g of probe DNA was heat-denatured, chilled and added to 5 ml of prehybridisation buffer. The membrane was hybridised at 68 °C overnight.

For washing and probe detection, the membrane was washed twice in 50 ml 2x SSC, 0.1% SDS at room temperature for five minutes, then twice in 50 ml 0.1x SSC, 0.1% SDS at 68 °C for 15 minutes. The membrane was equilibrated for one minute in TS buffer (100 mM Tris HCl pH 7.5, 150 mM NaCl), then blocked for 30 minutes in TSB buffer (TS buffer plus 1% w/v blocking reagent). Anti-DIG-alkaline phosphatase antibody conjugate was diluted 1:5000 in TSB buffer and the membrane was incubated in this solution for 30 minutes. The membrane was washed twice for 15 minutes with TS buffer and equilibrated for two minutes in substrate buffer (100 mM Tris-HCl pH 9.5, 100 mM NaCl, 50 mM MgCl$_2$). The bound probe was detected colorimetrically by incubating the membrane in the dark without shaking in 20 ml of substrate buffer containing 400 $\mu$M nitroblue tetrazolium and 400 $\mu$M 5-bromo-4-chloro-3-indolyl phosphate. Colour development was stopped by washing the membrane in TE buffer.

#### DNA sequencing methods
Plasmid DNA was sequenced by the dideoxy-chain termination method (Sanger, 1977 [@sanger_dna_1977]), using the Sequenase 2.0 kit (Amersham). Sequencing was divided into three stages: template denaturation plus primer annealing, labelling and termination.

1 $\mu$g of plasmid DNA was denatured either by boiling for five minutes then chilling on ice, or by incubation in 0.2 M NaOH for 5 minutes at 37 °C. In the latter case, the NaOH was neutralised with 0.2 M HCl after denaturation. Approximately 1 pmol of sequencing primer was annealed to the template at 37 °C for 10 minutes, in a volume of 10 $\mu$l. The DNA labelling reaction comprised the 10 $\mu$l solution of annealed DNA template plus primer, which was made up to a final volume of 16 $\mu$l containing the following components: $^{35}$S-dATP (6.25 $\mu$Ci), DTT (3.2 mM), Sequenase reaction buffer (40 mM Tris-HCl pH 7.5, 50 mM NaCl, 20 mM MgCl$_2$), 0.25 $\mu$M each of dCTP, dGTP and dTTP, and 1.6 units of Sequenase enzyme. In some reactions two optional additions were made: (1) 3.2 mM MnCl$_2$ plus 5 mM sodium isocitrate, which permitted reading of the sequence closer to the primer, and/or (2) 7% v/v DMSO, which alleviated the problem of secondary structure formation during extension of the labelled DNA fragments. The labelling reaction was incubated at room temperature for five minutes. Following labelling, the reaction mix was divided into four aliquots and each of these was mixed with 2.5 $\mu$l of termination mixture (which contained 80 $\mu$M of each dNTP plus 8 $\mu$M of the appropriate dideoxy-NTP, in 50 mM NaCl). The termination reactions were performed at 42 °C for five minutes. In some reactions DMSO was added to a concentration of 7% v/v, to eliminate the formation of secondary structure as described above. Finally, each reaction was inactivated with the addition of 4 $\mu$l of stop solution (95% v/v formamide, 20 mM Na$_2$EDTA, 0.05% w/v each of bromophenol blue and xylene cyanol FF). 3.5 $\mu$l of the A, C, G and T termination reactions were electrophoresed side by side on a 6% acrylamide sequencing gel, in TBE buffer at a constant power of 70 W. Following separation the gel was dried under vacuum at 80 °C and exposed to X-ray film.

PCR products were sometimes sequenced directly from low melting point agarose gels (Kretz and O'Brien, 1993 [@kretz_direct_1993]). Following electrophoresis on 1% agarose gels (NuSieve GTG), a gel slice containing the PCR product was melted at 68 °C. The DNA was denatured by boiling, chilled on ice and annealed to approximately 1 pmol of primer in a volume of 10 $\mu$l as described for plasmid DNA. Subsequent sequencing reactions were carried out as described above, except that labelling was at 37 °C, to prevent solidification of the agarose.

#### Computer analysis of DNA data
Most DNA data analysis was performed using the GCG8-Open VMS and UNIX software suite (Devereux et al., 1984 [@devereux_comprehensive_1984], Genetics Computer Group, Wisconsin, USA), maintained at the William Dunn School of Pathology, University of Oxford. Freely-available software on the World Wide Web was also used widely and is referred to in the relevant chapters.

#### Oligonucleotide synthesis and preparation
Oligonucleotides for sequencing, PCR and primer extension were synthesised by Val Cooper at the Oligonucleotide Synthesis Service, Dyson Perrins Organic Chemistry Laboratory, University of Oxford. Before use, oligonucleotides were incubated at 55 °C overnight to evaporate residual ammonia. They were then recovered by ethanol precipitation and redissolved in sterile distilled water.

### RNA manipulation

#### Extraction of total RNA from _Thiosphaera pantotropha_
No single published protocol was used to isolate total RNA from cells of _Thiosphaera pantotropha_; the protocol described below was based on the methods described by Chattopadhyay et al. (1993) [@chattopadhyay_inexpensive_1993] and Majumdar et al. (1991) [@majumdar_simultaneous_1991]. 50 ml cultures were grown to mid-exponential phase, harvested by centrifugation and lysed in 4 ml of lysis buffer (1% SDS, 1 mM EDTA pH 8.0). The lysate was extracted with 4 ml of phenol:chloroform, saturated with 2 M sodium acetate pH 4.0 and centrifuged at 4000 g for 10 minutes, 4 °C. The aqueous phase was then re-extracted with 4 ml of chloroform and recovered by centrifugation. 0.8 volumes of isopropanol was added and the mixture was incubated on ice for 30 minutes, then centrifuged at 15 000 g for 15 minutes at 4 °C. The precipitated nucleic acids were redissolved in 200 $\mu$l of DNase buffer (40 mM Tris-HCl pH 8.0, 10 mM NaCl, 6 mM CaCl$_2$), containing 100 units of RNase-free DNase and incubated at 37 °C for 30 minutes. After DNase treatment, the mixture was extracted once more with an equal volume of phenol:chloroform and the RNA was ethanol-precipitated by incubating at -70 °C, followed by centrifugation at 15 000 g for 15 minutes, 4 °C. The pellet was washed with 100 $\mu$l of ice-cold 70 % v/v ethanol, air-dried and redissolved in 100 $\mu$l of RNase-free water.

RNA quality was analysed by the absorbance ratio A$_{260}$:A$_{280}$ and by denaturing gel electrophoresis (Section 2.5.32).

#### Formaldehyde-agarose gel electrophoresis
Denaturing agarose gel electrophoresis in the presence of formamide was used to examine the integrity of RNA preparations and to separate RNA molecules by size before transfer to a membrane for Northern blotting. Up to 20 $\mu$g of total RNA in 4.5 $\mu$l was made up to a volume of 20 $\mu$l, in MOPS buffer (20 mM morpholinopropanesulphonic acid pH 7.0, 5 mM sodium acetate, 0.5 mM EDTA) containing 50% v/v freshly deionised formamide and 2.2 M formaldehyde. The RNA was denatured by heating at 80 °C for 3 minutes, then placed on
ice. 1% formaldehyde-agarose gels were prepared by dissolving 1 g of agarose in a 50 ml solution containing MOPS buffer and 2.2 M formaldehyde. 4 $\mu$l of loading dye (50% v/v glycerol, 1 mM EDTA, 0.4 % w/v bromophenol blue, 33 ng $\mu$l$^{-1}$ ethidium bromide) was added to the RNA samples before loading and the gel was run at a constant voltage of 100 V for 5-6 hours. Gels were examined and photographed under ultraviolet light.

#### Northern blotting
Northern blotting was used to detect specific mRNA transcripts from denitrification genes in _T. pantotropha_. The method used closely followed that of Engler-Blum et al. (1993) [@engler-blum_reduction_1993]. Following formaldehyde-agarose gel electrophoresis, the gel was washed with 20x SSC for 20 minutes. RNA was then transferred to a positive nylon membrane (Boehringer Mannheim) by capillary transfer with 20x SSC at 4 °C and crosslinked to the membrane using UV illumination. A lane containing molecular size markers was cut from the membrane and stained with methylene blue (0.2% w/v in 0.2 M sodium acetate pH 4.7). The membrane was prehybridised for one hour at 68 °C in a high SDS phosphate buffer (250 mM sodium phosphate pH 7.2, 1 mM EDTA, 20% w/v SDS). A DIG labelled dsDNA probe (Section 2.5.22) was hybridised to the RNA in 10 ml of the same buffer at 68 °C overnight. The membrane was washed three times for 20 minutes each at 65 °C in 50 ml of H-wash buffer (20 mM sodium phosphate pH 7.2, 1% w/v SDS, 1 mM EDTA), then once for five minutes in W-wash buffer (100 mM maleic acid pH 8.0, 3 M NaCl, 0.3% v/v Tween-20) and blocked for one hour in blocking buffer (W-wash buffer plus 0.5% w/v blocking reagent, Boehringer Mannheim). DIG antibody-alkaline phosphatase conjugate was diluted 1:10 000 in blocking buffer and the membrane was incubated with 20 ml of this buffer for 30 minutes. The membrane was then washed four times for 10 minutes each with W-wash buffer and equilibrated for five minutes in substrate buffer (100 mM Tris-HCl pH 9.5, 100 mM NaCl, 50 mM MgCl$_2$).

The hybridised probe was detected either colorimetrically or by chemiluminescence. For colorimetric detection, the membrane was incubated with 20 ml of colour solution (Section 2.5.22) in the dark without shaking until bands appeared. Development was stopped by washing with TE buffer. For chemiluminescent detection, the alkaline
phosphatase substrate CSPD (Boehringer Mannheim) was diluted 1:100 in 1 ml of substrate buffer and pipetted onto the membrane. Following a five minute incubation in the dark, excess solution was removed and the membrane was incubated in a sealed hybridisation bag at 37 °C for 15 minutes. The membrane was then exposed to X-ray film (Kodak), initially for one hour, until exposed bands appeared on the film.

#### Primer extension analysis
Primer extension was used to determine the 5'-end of the _nirS_ gene mRNA transcript. The procedure was divided into 3 stages: oligonucleotide labelling, primer-RNA annealing and cDNA extension. 10 pmol of oligonucleotide was end-labelled in a 20 $\mu$l reaction containing kinase buffer (70 mM Tris-HCl pH 7.6, 10 mM MgCl$_2$, 5 mM DTT), 50 $\mu$Ci of $\gamma^{32}$P-ATP and 8 units of polynucleotide kinase, exactly as described in Sambrook (1989). The labelled oligonucleotide was redissolved in 100 $\mu$l of TE buffer and could be stored at -20 °C for up to 1 week.

1 $\mu$l (approximately 109 cpm) of labelled primer was annealed to 40 $\mu$g of heat denatured RNA in 20 $\mu$l of annealing buffer (2 mM Tris-HCl pH 7.9, 250 mM KCl, 0.2 mM EDTA) at 50 °C for 90 minutes. The annealed primer-RNA was then ethanol-precipitated, redissolved in 20 $\mu$l of reverse transcription mix (50 mM Tris-HCl pH 8.3, 75 mM KCl, 3 mM MgCl$_2$, 10 mM DTT, 1.3 mM each dNTP, 20 units RNasin inhibitor, 50 $\mu$g ml$^{-1}$ actinomycin D, 33 units AMV reverse transcriptase) and incubated at 37 °C for 2 hours. DNA synthesis was stopped with 25 mM EDTA, pH 8.0. The mixture was treated with RNase at 37 °C for 20 minutes, extracted with phenol-chloroform, ethanol-precipitated and redissolved in 4 $\mu$l of TE buffer. 6 $\mu$l of sequencing stop solution was added and the labelled cDNA was run on a 6% acrylamide sequencing gel alongside a reference sequencing ladder generated using the same primer.

#### 5'-RACE (Rapid amplification of cDNA 5' ends)
5'-RACE was used as an alternative method to determine the 5'-end of mRNA transcripts. The procedure used closely followed that of Frohman (1993) [@frohman_rapid_1993]. 10 $\mu$g of total RNA was reverse-transcribed using the _nirS_ sequence specific primer 284R (5'-GACATCCTGCTGCGCAAGGT-3'). The mixture was then diluted with TE buffer, excess primer and nucleotides were removed by centrifugation through a Centricon-100 filter and the cDNA was recovered on a Millipore spin filter in 10 $\mu$l of TE buffer. Addition of the poly-dATP tail and the two subsequent nested PCR amplifications were performed exactly as described by Frohman (1993), using the forward primers Q$_T$, Q$_0$ and Q$_1$ (detailed in Frohman, 1993) and the sequence specific reverse primers 242R (5'-ATAGTCGGTGCGCGTCTT-3') and 228R (5P-TCTTGTGGTCCTCCAGCG-3'). PCR products were analysed by electrophoresis on 1.2% agarose gels, cloned into the pGEM-T vector and sequenced using M13 universal primers.

