# Conclusions and future research perspectives {#chapter08}

The aims of the present work were two-fold: first, to clone and sequence the _nirS_ gene from _T. pantotropha_, so as to be able to compare cytochrome _cd_$_1$ nitrite reductase from this organism with the enzyme from other sources, and second, to investigate systems by which the _nirS_ gene could be expressed so as to yield a holoprotein containing both the _c_- and the _d_$_1$ haems. The ultimate goal of this work, which is beyond the scope of the present project, is to construct a number of site-directed mutants of cytochrome _cd_$_1$ in which the key residues, such as the haem ligands and the histidines at the active site, are altered. This would allow the role of these residues to be more clearly defined.

In Chapter 3, the sequence of the _nirS_ gene and its product, cytochrome _cd_$_1$ was reported. Knowledge of the cytochrome _cd_$_1$ protein sequence has allowed the crystal
structure to be refined to 1.28 $\unicode{x212b}$ and has confirmed the haem ligands in the oxidised form (His-17 and His-69 at the _c_-haem, Tyr-25 and His-200 at the _d_$_1$ haem). The sequence also
confirms that eight N-terminal residues are not visible in the crystal structure because of disorder in the crystal packing. The major finding in Chapter 3 was that the haem ligands
His-17 and Tyr-25 are not conserved in the cytochrome _cd_$_1$ family. This was a surprising finding in view of the overall high similarity of the protein sequences and some implications for the catalytic mechanism of the enzyme were discussed. It was noted that structural data for cytochrome _cd_$_1$ from other organisms would be a valuable addition to the current data. Very recently, the structure of cytochrome _cd_$_1$ in the oxidised state from _Ps. aeruginosa_ has been solved [@cutruzzola_mutagenesis_1997]. Although the structure itself has not yet been published, some of the details have been made available. The _c_-haem is ligated by a methionine and a histidine residue, as was predicted from MCD spectroscopy for cytochrome _cd_$_1$ both from _Ps. aeruginosa_ [@sutherland_investigation_1986] and from _Ps. stutzeri_ Zobell [@cheesman_two_1997]. The _d_$_1$ haem is ligated by histidine and by a hydroxide ion. Interestingly, _Ps. aeruginosa_ cytochrome _cd_$_1$ is the only other example, apart from that of _T. pantotropha_ cytochrome _cd_$_1$, of a cytochrome _cd_$_1$ with a tyrosine residue close to the N-terminus of the protein. In the case of _Ps. aeruginosa_ this tyrosine, Tyr-10, does not act directly as a ligand to the _d_$_1$ haem, but is instead hydrogen-bonded to the hydroxide ion which in turn is the sixth ligand to the _d_$_1$ haem. Furthermore, replacement of Tyr-10 with phenylalanine has no effect on the catalytic activity, optical spectroscopy or electron transfer kinetics of _Ps. aeruginosa_ cytochrome _cd_$_1$ [@cutruzzola_mutagenesis_1997]. These data strengthen the case for significant structural and mechanistic differences between the cytochromes _cd_$_1$, but also emphasise the importance of assessing the role of Tyr-25 in the _T. pantotropha_ enzyme using as many approaches as possible.

Chapters 4 to 6 of the present work were concerned with the expression of the cloned _nirS_ gene in different systems. In Chapter 4 it was shown that the _T. pantotropha_ _nirS_ gene
could be expressed in _E. coli_ to give a semi-apo protein containing only _c_-type haem. It was then possible to reconstitute the recombinant protein with purified _d_$_1$ haem, producing a protein with some of the spectroscopic and catalytic features of the native enzyme. This approach will be of use in the production of site-directed mutants that are structurally unstable or enzymically inactive when expressed as the holoprotein. Such mutants would not support the growth of the host organism under denitrifying conditions and so little or no protein could be  recovered for further studies. However, provided that the semi-apo form of the mutant protein was stably maintained in _E. coli_, it should be possible to reconstitute the recombinant protein as described. Future work in this area will require improvements in the yield of recombinant protein and the optimisation of the reconstitution protocol.

Chapter 5 described the expression of the _T. pantotropha_ _nirS_ gene in _Ps. aeruginosa_. In this case, it was hoped that the recombinant protein would be able to sequestrate the _d_$_1$ haem that was synthesised by the host organism, so as to yield the active holoenzyme. However, some difficulties were experienced both with the solubility of the recombinant
enzyme during anaerobic growth and with the DNA construct used. It appeared that the presence of either the regulatory region upstream of the cloned _nirS_ gene or that of the
truncated downstream _nirE_ gene had an adverse effect on the growth of the host cells. In future work using any heterologous host organism, a DNA construct containing only the
structural gene, _nirS_, is recommended. Nevertheless, recombinant cytochrome _cd_$_1$ with some of the spectroscopic and catalytic properties of the native enzyme was produced, and
this system could be of use for identifying mutants of cytochrome _cd_$_1$ in which enzymatic activity has been completely abolished.

Chapter 6 detailed the construction of a _nirS_ deletion mutant in _T. pantotropha_ and its use as a host for expression of the cloned _nirS_ gene. It was shown that the mutant could be complemented with the wild-type gene on a low copy number plasmid, fully restoring anaerobic growth on nitrate with no deleterious effects. However, expression of a
cytochrome _cd_$_1$ mutant in which the _d_$_1$ haem ligand, Tyr-25, was replaced with phenylalanine did not restore growth to the deletion mutant strain; furthermore, the amount
of expressed enzyme was extremely low, indicating that it may have been degraded. These data indicate that Tyr-25 is an essential residue for the function of _T. pantotropha_
cytochrome _cd_$_1$, although strictly, as the recombinant protein could not be isolated, it was not possible to determine whether Tyr-25 is essential for catalytic activity. However, this interpretation of the data is very plausible; it may be that as the cells are incapable of nitrite reduction, they are placed under stress because of the accumulation of nitrite and the inactive cytochrome _cd_$_1$ is degraded as part of a general stress response. The presence of elevated levels of pseudoazurin, cytochrome _c_ peroxidase and a previously unidentified _c_-type cytochrome may also all be indications of a stress response. These data illustrate the problem of expressing a cytochrome _cd_$_1$ mutant that cannot support the growth of the host organism under denitrifying conditions. Possible solutions to this problem may include (1) the co-expression of a copper nitrite reductase in the deletion mutant strain, which would allow denitrifying growth and also the isolation of the mutant cytochrome _cd_$_1$, and (2) investigation of the expression of cytochrome _cd_$_1$ mutants under different growth conditions. So far is as known, the genes for _d_$_1$ biosynthesis, as well as the _nirS_ gene, are activated during anaerobic, denitrifying growth, but further understanding of the regulation of denitrification may reveal a way in which aerobic expression of these genes can be achieved.

Finally, in Chapter 7, the transcription of the _nirS_ gene was explored. It was shown that the _nirS_ gene was transcribed as a monocistronic mRNA. The transcription start site of
the gene was also identified. The former result was of some importance, as it established that the _nirS_ deletion described in Chapter 6 could be constructed without disruption of the
_d_$_1$ biosynthesis genes situated downstream of the _nirS_ gene. Additionally, an analysis of some of the denitrification gene sequences that are currently known indicates a common
regulatory mechanism and strongly suggests that these genes are transcribed using a specific sigma factor. However, it is abundantly clear that at present, very little is understood of the transcriptional regulation of denitrification genes, and a number of future experiments in this direction were proposed at the end of Chapter 7. Elucidating the regulation and function of the many denitrification genes that have been identified looks certain to be the major challenge in the field of denitrification research in future years.
